### ISSUE TITLE
[Feature request]Is it possible to add a password to the result batch file?

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [AveYo/res2batch#1]
Is it possible to add a password to the result batch file? When you compress files or folder, you provide a password. When the user click the generated batch file, you need to type the correct password before it generates the original files. This would make the program more useful. Thanks.

**Comment by AveYo** [comment]
Featured in **v6.0**!
- GUI prompt to input key, for convenience
- encoding / decoding key is used as the password
- BAT85 has a 85 characters key, while BAT91 has a 91 characters key
- it is saved in an external `output~key.ini` file
- to make it meaningful select option 2: Randomize decoding key
- strength is good enough _(85-6 or 91-6 *factorial combinations)_

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Awesome! Thank you!

**Comment by AveYo** [comment]
@yangshuairocks - note that I have re-released 6.0 (final) to iron out some corner case issues, so you should re-download it

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thank you!

**Comment by AveYo** [comment]
@yangshuairocks - v6.1 final is up, fixed most corner cases I found - notable skipping access denied files and using real desktop or send to folder in case user changed special folder's location.  
Also removed the 2-pass makecab since it was rather pointless in practice.  
Default choices set to none, resulting in preffered BAT85 encode with LZX compress and long lines.  
If ``<*`%\>`` characters are not an issue for you, go for BAT91 option!  
If target is incompressible (already an archive / solid / random file), go for No LZX compression!  
That's all! 🥇

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks again! I've updated.
