### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jose89fcb** [AveYo/res2batch#2]
when i run the .bat this comes out

https://i.imgur.com/Mw4lWwp.png

https://i.imgur.com/9dzZiUm.png

any solution?

**Comment by paulstelian97** [comment]
Can you leave the command used to compress the file? You shouldn't give the output archive file name as a parameter; otherwise it might try to compress itself which will lead to invalid data.

Also avoid having the archive and the file you compress have the same name (this might mean you cannot compress .cmd files)

**Comment by AveYo** [comment]
There might be script bug, it would help if you could send a small sample

**Comment by jose89fcb** [comment]
> Puede haber un error de script, sería útil si pudiera enviar una pequeña muestra

this is the code:
https://pastebin.com/1W2mqb37

**Comment by paulstelian97** [comment]
I cannot see anything related to Compressed2TXT in that code you pasted.

**Comment by AveYo** [comment]
Tx for the code but I meant the compressed output.  
I'm thinking there must be a Spanish-localization issue
